// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkUUz9pJaMSyIDERoTxvhDVCx88Ku0eT0',
    appId: '1:480471654399:web:e007bcf336c0af55e491ca',
    messagingSenderId: '480471654399',
    projectId: 'smartupchallenge-390e5',
    authDomain: 'smartupchallenge-390e5.firebaseapp.com',
    storageBucket: 'smartupchallenge-390e5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOtJR4ay3Nnc3LHMW5sbaGsSeGQaJtlpo',
    appId: '1:480471654399:android:33bdab9dfe5be236e491ca',
    messagingSenderId: '480471654399',
    projectId: 'smartupchallenge-390e5',
    storageBucket: 'smartupchallenge-390e5.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkUUz9pJaMSyIDERoTxvhDVCx88Ku0eT0',
    appId: '1:480471654399:web:5ddaf3ceb446c315e491ca',
    messagingSenderId: '480471654399',
    projectId: 'smartupchallenge-390e5',
    authDomain: 'smartupchallenge-390e5.firebaseapp.com',
    storageBucket: 'smartupchallenge-390e5.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGivfuN59visWd4fT403Ryhr6bHVK2HRc',
    appId: '1:480471654399:ios:bd12a54781bb6febe491ca',
    messagingSenderId: '480471654399',
    projectId: 'smartupchallenge-390e5',
    storageBucket: 'smartupchallenge-390e5.appspot.com',
    iosBundleId: 'com.example.smartupChallenge',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGivfuN59visWd4fT403Ryhr6bHVK2HRc',
    appId: '1:480471654399:ios:bd12a54781bb6febe491ca',
    messagingSenderId: '480471654399',
    projectId: 'smartupchallenge-390e5',
    storageBucket: 'smartupchallenge-390e5.appspot.com',
    iosBundleId: 'com.example.smartupChallenge',
  );

}